spring.application.name=api-operaciones
server.port=8080

services.transacciones.url=http://localhost:8081

# 32 bytes en Base64. Para la evaluación se comparte la misma llave con el front.
security.aes.key-base64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
